Repository Nerzal/gocloak, pull requests merged in 2019-12, with the labels that each got.

#108 adding GetGroupMembers to goclock client
  README.md
  client.go
  client_test.go
  gocloak.go
Labels: enhancement

#109 Add full group representation
  client_test.go
  models.go
Labels: enhancement

#111 Pointers
  .travis.yml
  client.go
  client_test.go
  gocloak.go
  model_test.go
  models.go
  pkg/jwx/jwx.go
  utils.go
  utils_test.go
Labels: backward incompatible, bug

#112 Retrive an ID of a created object from Location header
  client.go
  client_test.go
  gocloak.go
Labels: backward incompatible, enhancement

#113 Adding CreateChildGroup method
  README.md
  client.go
  client_test.go
  gocloak.go
Labels: enhancement

#122 Properly returning permission data when introspecting rpt
  client_test.go
  models.go
Labels: bug
