Repository Nerzal/gocloak, pull requests merged in 2019-06, with the labels that each got.

#69 Add GetServerInfo function
  README.md
  client.go
  client_test.go
  gocloak.go
  models.go
Labels: enhancement

#70 Update models.go
  models.go
Labels: enhancement

#71 Fix typos int Client representation
  models.go
Labels: bug

#66 Refactoring
  README.md
  client.go
  client_test.go
  errors.go
  go.mod
  gocloak.go
  models.go
  tools/bump_version.go
Labels: backward incompatible, enhancement

#83 Adding method to regenerate a client secret using the Keycloak API
  README.md
  client.go
  client_test.go
  gocloak.go
Labels: enhancement

#81 Update models.go
  models.go
Labels: enhancement

#80 Added GetClientScope Method
  README.md
  client.go
  client_test.go
  gocloak.go
Labels: enhancement
